export const OBTENER_TEMAS = "OBTENER_TEMAS";
export const AGREGAR_TEMA = "AGREGAR_TEMA";
export const IMAGEN_SUBIDA = "IMAGEN_SUBIDA";

export const INICIAR_SESION_EXITO = "INICIAR_SESION_EXITO";
export const INICIAR_SESION_ERROR = "INICIAR_SESION_ERROR";
export const USUARIO_AUTENTICADO = "USUARIO_AUTENTICADO";
export const CERRAR_SESION = "CERRAR_SESION";

export const CARGANDO = "CARGANDO";
